{"name": "test_invalidLogin", "status": "passed", "description": {"mark": {"name": "allure_description", "args": ["Verify User is not able to Login with Invalid credentials"]}}, "attachments": [{"name": "log", "source": "3acb593b-b9c2-4d44-a416-921951a099ad-attachment.txt", "type": "text/plain"}], "start": 1589015473561, "stop": 1589015485818, "uuid": "b8bbdb64-91a0-40ab-baee-337fe8f6db31", "historyId": "57f7ed73470ce8d4aacc4aec2dc80c63", "testCaseId": "e94f0024c374825736805ac54bd2db4c", "fullName": "tests.home.test_login.TestLogin#test_invalidLogin", "labels": [{"name": "severity", "value": "minor"}, {"name": "parentSuite", "value": "tests.home"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "del1-lhp-N01966"}, {"name": "thread", "value": "36228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.home.test_login"}]}